// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CollectionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentMonthTotal")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("YearToDateTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce2b8d8f-b2a6-42b2-a0e8-6dba415cd341"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4150),
                            CurrentMonthTotal = 5000.0,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4120),
                            Name = "Emergency",
                            YearToDateTotal = 30000.0
                        },
                        new
                        {
                            Id = new Guid("013eb7a6-bace-41bb-966a-a5dfb11bdfe6"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 10, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4160),
                            CurrentMonthTotal = 12000.0,
                            Date = new DateTime(2024, 10, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4150),
                            Name = "Retirement",
                            YearToDateTotal = 60000.0
                        },
                        new
                        {
                            Id = new Guid("8f518db6-44f7-4b0f-83e5-c29f474eb681"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 9, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4160),
                            CurrentMonthTotal = 8000.0,
                            Date = new DateTime(2024, 9, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4160),
                            Name = "Investment",
                            YearToDateTotal = 50000.0
                        },
                        new
                        {
                            Id = new Guid("b255647d-e73d-4e16-96e9-4a98f4a8e449"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 8, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4170),
                            CurrentMonthTotal = 3000.0,
                            Date = new DateTime(2024, 8, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4170),
                            Name = "Vacation",
                            YearToDateTotal = 15000.0
                        },
                        new
                        {
                            Id = new Guid("7f8067a6-b14b-4a06-a555-c6f36b6e336d"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 7, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4190),
                            CurrentMonthTotal = 7000.0,
                            Date = new DateTime(2024, 7, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4180),
                            Name = "Education",
                            YearToDateTotal = 35000.0
                        },
                        new
                        {
                            Id = new Guid("17f6da93-33aa-41d7-90e3-4e2629a666ab"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 6, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4190),
                            CurrentMonthTotal = 9000.0,
                            Date = new DateTime(2024, 6, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4190),
                            Name = "Business",
                            YearToDateTotal = 40000.0
                        },
                        new
                        {
                            Id = new Guid("b9e71397-917b-4b92-a625-eddb01888db6"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 5, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4190),
                            CurrentMonthTotal = 6000.0,
                            Date = new DateTime(2024, 5, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4190),
                            Name = "Health",
                            YearToDateTotal = 28000.0
                        },
                        new
                        {
                            Id = new Guid("8b0bf32a-305c-409a-b681-36652caa6996"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4200),
                            CurrentMonthTotal = 1500.75,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4200),
                            Name = "Utilities",
                            YearToDateTotal = 12000.0
                        },
                        new
                        {
                            Id = new Guid("4e6bf374-269c-4805-85d1-0760ea0b6831"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4200),
                            CurrentMonthTotal = 3000.0,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4200),
                            Name = "Living Expenses",
                            YearToDateTotal = 25000.0
                        },
                        new
                        {
                            Id = new Guid("e68a33fa-786a-4475-9894-9adc7c5b7170"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4210),
                            CurrentMonthTotal = 2000.5,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4200),
                            Name = "Savings",
                            YearToDateTotal = 18000.0
                        },
                        new
                        {
                            Id = new Guid("62733967-65e7-4859-97b2-9e078da0a8fe"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4210),
                            CurrentMonthTotal = 1200.0,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4210),
                            Name = "Travel",
                            YearToDateTotal = 10000.0
                        },
                        new
                        {
                            Id = new Guid("cbd6cd10-58c3-4a2a-9bdc-f9aa3d673a68"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4210),
                            CurrentMonthTotal = 800.0,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4210),
                            Name = "Entertainment",
                            YearToDateTotal = 7000.0
                        },
                        new
                        {
                            Id = new Guid("48aef32a-0d95-43ac-94d5-a982b2abddd2"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4220),
                            CurrentMonthTotal = 900.0,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4220),
                            Name = "Groceries",
                            YearToDateTotal = 8000.0
                        },
                        new
                        {
                            Id = new Guid("cfc2aa39-7e43-4423-b44d-aa5fae30941a"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4220),
                            CurrentMonthTotal = 650.25,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4220),
                            Name = "Healthcare",
                            YearToDateTotal = 5000.0
                        },
                        new
                        {
                            Id = new Guid("50f18adb-764c-4bc3-8c2c-323ea7b2e7b9"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4230),
                            CurrentMonthTotal = 1300.0,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4220),
                            Name = "Education",
                            YearToDateTotal = 11000.0
                        },
                        new
                        {
                            Id = new Guid("2e33491f-0e02-4de8-b150-4306c05323a6"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4230),
                            CurrentMonthTotal = 400.0,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4230),
                            Name = "Miscellaneous",
                            YearToDateTotal = 3000.0
                        },
                        new
                        {
                            Id = new Guid("bc32ff64-4146-41da-916a-f69bc7752b42"),
                            CollectionType = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4230),
                            CurrentMonthTotal = 600.5,
                            Date = new DateTime(2024, 11, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4230),
                            Name = "Insurance",
                            YearToDateTotal = 4500.0
                        },
                        new
                        {
                            Id = new Guid("861b326c-225d-445d-ad2a-78f7cbdd8e4b"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 10, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4240),
                            CurrentMonthTotal = 10000.0,
                            Date = new DateTime(2024, 10, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4240),
                            Name = "Emergency Fund",
                            YearToDateTotal = 50000.0
                        },
                        new
                        {
                            Id = new Guid("71790a14-6074-4d68-a114-a6f299e7f13f"),
                            CollectionType = 0,
                            CreatedAt = new DateTime(2024, 9, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4240),
                            CurrentMonthTotal = 15000.0,
                            Date = new DateTime(2024, 9, 14, 22, 34, 33, 550, DateTimeKind.Local).AddTicks(4240),
                            Name = "Retirement Fund",
                            YearToDateTotal = 70000.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExpenseCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCollectionId");

                    b.HasIndex("FundCollectionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Entities.Collection", "ExpenseCollection")
                        .WithMany()
                        .HasForeignKey("ExpenseCollectionId");

                    b.HasOne("Domain.Entities.Collection", "FundCollection")
                        .WithMany()
                        .HasForeignKey("FundCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCollection");

                    b.Navigation("FundCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
