import { Transaction, TransactionType } from "./type";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    fundCollectionId: "1",
    expenseCollectionId: "1",
    transactionType: TransactionType.Credit,
    description: "Initial Fund Deposit",
    amount: 5000.0,
    date: "2024-01-01T10:00:00",
  },
  {
    id: "2",
    fundCollectionId: "1",
    expenseCollectionId: "1",
    transactionType: TransactionType.Debit,
    description: "Office Supplies Purchase",
    amount: 150.75,
    date: "2024-01-05T14:30:00",
  },
  {
    id: "3",
    fundCollectionId: "1",
    expenseCollectionId: "2",
    transactionType: TransactionType.Debit,
    description: "Marketing Campaign Expense",
    amount: 620.0,
    date: "2024-01-10T09:15:00",
  },
  {
    id: "4",
    fundCollectionId: "2",
    expenseCollectionId: "1",
    transactionType: TransactionType.Credit,
    description: "Fundraising Event Income",
    amount: 2000.0,
    date: "2024-01-15T11:00:00",
  },
  {
    id: "5",
    fundCollectionId: "2",
    expenseCollectionId: "2",
    transactionType: TransactionType.Debit,
    description: "Consulting Services Payment",
    amount: 800.0,
    date: "2024-01-20T16:45:00",
  },
  {
    id: "6",
    fundCollectionId: "3",
    expenseCollectionId: "3",
    transactionType: TransactionType.Credit,
    description: "Monthly Donation",
    amount: 1200.0,
    date: "2024-02-01T12:00:00",
  },
  {
    id: "7",
    fundCollectionId: "3",
    expenseCollectionId: "4",
    transactionType: TransactionType.Debit,
    description: "Travel Expenses Reimbursement",
    amount: 400.0,
    date: "2024-02-05T08:30:00",
  },
  {
    id: "8",
    fundCollectionId: "1",
    expenseCollectionId: "3",
    transactionType: TransactionType.Debit,
    description: "Office Rent Payment",
    amount: 2000.0,
    date: "2024-02-10T09:00:00",
  },
  {
    id: "9",
    fundCollectionId: "2",
    expenseCollectionId: "5",
    transactionType: TransactionType.Credit,
    description: "Grant Received",
    amount: 3000.0,
    date: "2024-02-15T10:30:00",
  },
  {
    id: "10",
    fundCollectionId: "2",
    expenseCollectionId: "6",
    transactionType: TransactionType.Debit,
    description: "Annual Audit Fees",
    amount: 1500.0,
    date: "2024-02-20T14:00:00",
  },
];
